### ISSUE TITLE
README ?

### ISSUE THREAD

**Issue by stuaxo** [t0rakka/mango-examples#1]
Hi,
   I came here from here:
https://www.facebook.com/permalink.php?story_fbid=1799575323610310&id=100006735798590

any chance of a tiny readme explaning what this is ?

S

**Comment by t0rakka** [comment]
It's just some code that I am sharing with my friends. The short version: utility code that I need in almost every program or project I am working on and it gets dumbed into the library after a while. So it's code that I need all the time. I do graphics programming so it's related to that. I'll try to come up with something eventually. Thanks for asking, very nice of you.

**Comment by t0rakka** [comment]
Added readme. I hope this concludes the issue. :)

**Comment by stuaxo** [comment]
Awesome, I know it's a bit cheeky going around asking for things, but was genuinely curious after seeing the comment above.
