### ISSUE TITLE
jpeg benchmark build error with opencv

### ISSUE THREAD

**Issue by nrobin** [t0rakka/mango-examples#3]
uncommented define TEST_OCV
and build benchmark. It has some error my system
build env is below
os aarch64 ubuntu 16.04 docker image
opencv : 3.4.3 (/usr/local/lib)

CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `ocv_load_jpeg(char const*)':
benchmark.cpp:(.text+0x1c49c): undefined reference to `cv::imread(cv::String const&, int)'
CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `main':
benchmark.cpp:(.text+0x1c8f8): undefined reference to `cv::imread(cv::String const&, int)'
benchmark.cpp:(.text+0x1c940): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `cv::String::String(char const*)':
benchmark.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4c): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `cv::String::~String()':
benchmark.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x10): undefined reference to `cv::String::deallocate()'
CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `cv::Mat::~Mat()':
benchmark.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x34): undefined reference to `cv::fastFree(void*)'
CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `cv::Mat::release()':
benchmark.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x58): undefined reference to `cv::Mat::deallocate()'
CMakeFiles/benchmark.dir/benchmark.cpp.o: In function `cv::Mat::operator=(cv::Mat&&)':
benchmark.cpp:(.text._ZN2cv3MataSEOS0_[_ZN2cv3MataSEOS0_]+0xf4): undefined reference to `cv::fastFree(void*)'
collect2: error: ld returned 1 exit status
jpeg_benchmark/CMakeFiles/benchmark.dir/build.make:94: recipe for target 'jpeg_benchmark/benchmark' failed
make[2]: *** [jpeg_benchmark/benchmark] Error 1
CMakeFiles/Makefile2:413: recipe for target 'jpeg_benchmark/CMakeFiles/benchmark.dir/all' failed
make[1]: *** [jpeg_benchmark/CMakeFiles/benchmark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nrobin** [comment]
Thank you
I also solved the problem in the same way.
And I have some question. 
Can I understand the load part as jpeg decoding time?
And Why is it different from the previous disable opencv?

diff --git a/jpeg_benchmark/CMakeLists.txt b/jpeg_benchmark/CMakeLists.txt
index b5468b2..589b602 100644
--- a/jpeg_benchmark/CMakeLists.txt
+++ b/jpeg_benchmark/CMakeLists.txt
@@ -1,2 +1,3 @@
+find_package(OpenCV REQUIRED)
 add_executable(benchmark benchmark.cpp)
-target_link_libraries(benchmark LINK_PUBLIC mango jpeg)
+target_link_libraries(benchmark LINK_PUBLIC mango jpeg ${OpenCV_LIBS})

root@apq8053:~/docker/mango-examples/build# jpeg_benchmark/benchmark /root/docker/scene00001.jpg 
load libjpeg: 22 ms
load stb:     175 ms
load mango:   42 ms
load opencv:  41 ms

save libjpeg: 55 ms
save stb:     463 ms
save mango:   20 ms
save opencv:  49 ms

image: 1280 x 738

**Comment by t0rakka** [comment]
It's probably variance between different runs.. probably should do N times, drop the fastest and slowest sample and compute the average from the remaining ones. 

The dropping is a good idea to eliminate random fluctuations on multi-tasking system. The disk or CPU might be doing something expensive Just Now that affects the results.

You can also run the benchmark N times and inspect the results and do some extrapolation form that. If the slow performance persists (it was ~ 20 ms, now ~40 ms?) then I can't really guess that it could be. I am on 6-core i9 laptop at the moment and the timings seem to be fairly consistent for me with and without the OpenCV code enabled.

**Comment by nrobin** [comment]
I understand. I will try to change my camera jpeg decode function. And I will report you. Have a nice day.
